In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Bangladesh-Crime-Dataset.csv")

In [3]:
df.head()

,Unnamed: 0,incident_month,incident_week,incident_weekday,weekend,part_of_the_day,latitude,longitude,incident_place,incident_district,...,literacy_rate,religious_institution,playground,park,police_station,cyber_cafe,school,college,cinema,crime
0,0,7,29,wednesday,0,morning,23.774569,90.355292,adabar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
1,1,1,2,wednesday,0,night,23.774569,90.355292,adabar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
2,2,1,4,tuesday,0,night,23.769808,90.351595,adabor,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
3,3,3,9,friday,1,night,23.728907,90.417137,aftabnagar,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
4,4,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder

In [4]:
df.shape

(6574, 38)

In [5]:
df["weekend"].unique()

array([0, 1])

In [6]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [12]:
df.head(25)

,incident_month,incident_week,incident_weekday,weekend,part_of_the_day,latitude,longitude,incident_place,incident_district,incident_division,...,literacy_rate,religious_institution,playground,park,police_station,cyber_cafe,school,college,cinema,crime
0,7,29,wednesday,0,morning,23.774569,90.355292,adabar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
1,1,2,wednesday,0,night,23.774569,90.355292,adabar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
2,1,4,tuesday,0,night,23.769808,90.351595,adabor,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
3,3,9,friday,1,night,23.728907,90.417137,aftabnagar,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
4,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
5,8,34,thursday,0,night,23.847177,90.404133,airport,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
6,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
7,1,1,saturday,1,evening,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
8,1,2,friday,1,evening,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
9,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
10,11,46,monday,0,morning,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
11,11,45,sunday,0,morning,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
12,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
13,2,7,saturday,1,morning,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
14,9,36,friday,1,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
15,6,23,monday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
16,4,14,sunday,0,morning,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
17,2,7,sunday,0,night,23.913894,90.320686,ashulia,dhaka,dhaka,...,68.0,1118,78,3,6,16,42,10,3,murder
18,7,31,monday,0,evening,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
19,5,19,tuesday,0,night,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
20,9,37,sunday,0,noon,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
21,8,31,thursday,0,night,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
22,1,3,thursday,0,night,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
23,7,31,monday,0,evening,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder
24,7,29,saturday,1,night,23.793708,90.453284,badda,dhaka,dhaka,...,74.6,4289,99,17,60,478,242,64,40,murder

In [16]:
df.gender_ration.unique()

array([125, 114, 101,  90, 113,  88, 116,  97,  96, 102,  98,  99, 110,
        94,  89,  86, 109, 107, 108, 100,  93, 103, 105, 104,  95, 117,
        91,  92, 106, 111, 203,  85,  84,  87])

In [14]:
df.precip.unique()

array([6.100e+00, 0.000e+00, 2.190e+01, 6.000e-01, 7.800e+00, 2.600e+00,
       1.030e+01, 2.300e+00, 7.000e+00, 2.100e+00, 1.100e+00, 1.230e+01,
       1.200e+00, 2.800e+01, 7.900e+00, 4.400e+00, 3.570e+01, 1.390e+01,
       2.720e+01, 3.100e+00, 8.000e-01, 3.800e+00, 5.100e+00, 3.400e+00,
       1.700e+00, 3.500e+00, 6.900e+00, 1.000e-01, 4.000e-01, 9.000e-01,
       1.000e+00, 8.200e+00, 7.600e+00, 1.010e+01, 5.040e+01, 1.910e+01,
       1.380e+01, 1.330e+01, 3.650e+01, 8.800e+00, 3.700e+00, 1.580e+01,
       5.500e+00, 7.100e+00, 8.100e+00, 1.800e+00, 4.300e+00, 5.000e+00,
       2.270e+01, 6.300e+00, 2.000e+00, 1.720e+01, 1.130e+01, 1.400e+00,
       1.500e+00, 5.000e-01, 5.900e+00, 9.200e+00, 2.000e-01, 1.570e+01,
       6.000e+00, 2.210e+01, 1.270e+01, 6.200e+00, 1.660e+01, 1.760e+01,
       1.250e+01, 1.000e+01, 1.170e+01, 1.730e+01, 2.500e+00, 7.300e+00,
       7.400e+00, 6.500e+00, 5.700e+00, 1.340e+01, 3.000e+00, 8.000e+01,
       1.140e+01, 2.870e+01, 4.200e+00, 4.510e+01, 2.000e+01, 9.100e+00,
       1.090e+01, 4.000e+00, 1.100e+01, 1.900e+00, 2.760e+01, 1.590e+01,
       2.670e+01, 8.000e+00, 3.000e-01, 1.220e+01, 7.200e+00, 4.100e+00,
       1.600e+00, 1.860e+01, 3.860e+01, 2.800e+00, 3.300e+00, 2.900e+00,
       5.600e+01, 1.210e+01, 8.400e+00, 4.900e+00, 3.870e+01, 2.200e+00,
       1.900e+01, 4.500e+00, 1.610e+01, 1.620e+01, 3.200e+00, 1.680e+01,
       1.050e+01, 7.000e-01, 2.700e+00, 9.400e+00, 1.150e+01, 1.790e+01,
       1.300e+00, 5.130e+01, 2.650e+01, 9.300e+00, 2.140e+01, 7.500e+00,
       6.400e+00, 1.120e+01, 1.500e+01, 2.660e+01, 2.770e+01, 1.700e+01,
       4.800e+00, 5.800e+00, 4.700e+00, 9.600e+00, 1.110e+01, 1.020e+01,
       1.360e+01, 1.060e+01, 1.260e+01, 1.280e+01, 3.600e+00, 2.180e+01,
       8.300e+00, 2.020e+01, 1.180e+01, 7.290e+01, 5.400e+00, 3.140e+01,
       3.560e+01, 1.290e+01, 2.570e+01, 4.600e+00, 1.430e+01, 1.820e+01,
       5.120e+01, 1.560e+01, 2.040e+01, 1.410e+01, 1.990e+01, 3.500e+01,
       3.610e+01, 2.480e+01, 3.230e+01, 5.300e+00, 1.510e+01, 1.240e+01,
       1.540e+01, 1.530e+01, 1.780e+01, 2.400e+00, 6.700e+00, 8.500e+00,
       2.430e+01, 2.540e+01, 5.060e+01, 5.200e+00, 1.310e+01, 2.370e+01,
       2.330e+01, 2.620e+01, 2.420e+01, 1.440e+01, 8.600e+00, 2.360e+01,
       2.390e+01, 1.550e+01, 2.150e+01, 2.910e+01, 1.070e+01, 3.020e+01,
       2.630e+01, 8.250e+01, 2.060e+01, 6.600e+00, 2.090e+01, 1.630e+01,
       4.750e+01, 2.880e+01, 1.940e+01, 2.580e+01, 9.020e+01, 2.600e+01,
       1.650e+01, 2.046e+02, 1.199e+02, 1.960e+01, 1.950e+01, 4.130e+01,
       2.260e+01, 8.700e+00, 4.070e+01, 7.840e+01, 2.170e+01, 9.700e+00,
       1.200e+01, 2.400e+01, 3.290e+01, 4.380e+01, 2.680e+01, 5.280e+01,
       1.600e+01, 1.190e+01, 8.970e+01, 5.550e+01, 2.730e+01, 2.890e+01,
       2.100e+01, 4.560e+01, 8.690e+01, 2.200e+01, 1.450e+01, 5.920e+01,
       3.310e+01, 3.640e+01, 2.410e+01, 4.430e+01, 9.500e+00, 1.554e+02,
       7.700e+00, 2.070e+01, 5.600e+00, 1.460e+01, 1.670e+01, 1.480e+01,
       2.850e+01, 3.600e+01, 9.800e+00, 2.010e+01, 2.980e+01, 3.060e+01,
       5.100e+01, 6.230e+01, 3.030e+01, 2.030e+01, 5.510e+01, 4.940e+01,
       3.720e+01, 1.251e+02, 2.690e+01, 4.040e+01, 2.790e+01, 2.310e+01,
       1.490e+01, 2.290e+01, 1.160e+01, 6.150e+01, 1.080e+01, 3.400e+01,
       2.640e+01, 1.880e+01, 1.850e+01, 2.590e+01, 3.700e+01, 1.350e+01,
       1.916e+02, 1.980e+01, 3.910e+01, 8.900e+00, 2.500e+01, 4.260e+01,
       2.300e+01, 2.510e+01, 2.120e+01, 3.380e+01, 3.730e+01, 4.080e+01,
       5.520e+01, 2.280e+01, 3.160e+01, 3.900e+00, 1.520e+01, 2.320e+01,
       3.100e+01, 2.380e+01, 1.640e+01, 1.800e+01, 1.740e+01, 2.440e+01,
       4.340e+01, 6.800e+00, 4.310e+01, 3.040e+01, 2.560e+01, 6.920e+01,
       3.170e+01, 4.200e+01, 1.750e+01, 6.260e+01, 9.900e+00, 1.770e+01,
       4.420e+01, 2.950e+01, 2.930e+01, 9.000e+00, 2.250e+01, 3.280e+01,
       4.600e+01, 1.320e+01, 4.000e+01, 3.410e+01, 3.930e+01, 3.740e+01,
       1.040e+01, 3.390e+01, 4.540e+01, 3.660e+01, 5.470e+01, 4.730e+01,
       1.690e+01, 1.370e+01, 5.210e+01, 1.920e+01, 1.420e+01, 3.490e+01,
       2.750e+01, 4.160e+01, 4.740e+01, 2.700e+01, 4.700e+01, 5.010e+01,
       2.520e+01, 1.840e+01, 1.890e+01, 2.900e+01, 1.400e+01, 6.940e+01,
       2.110e+01, 1.870e+01, 3.350e+01, 4.870e+01, 1.970e+01, 4.360e+01,
       3.710e+01, 2.740e+01, 3.750e+01, 7.190e+01, 2.840e+01, 4.030e+01,
       2.990e+01, 4.210e+01, 3.480e+01, 3.460e+01, 3.680e+01, 6.720e+01,
       6.880e+01, 4.820e+01, 4.490e+01, 3.590e+01, 4.890e+01, 6.350e+01,
       1.300e+01, 3.270e+01, 3.190e+01, 2.550e+01, 4.720e+01, 3.050e+01,
       3.220e+01, 2.960e+01, 2.830e+01, 4.670e+01, 5.290e+01, 3.430e+01,
       1.048e+02, 1.710e+01, 3.970e+01, 3.770e+01, 3.840e+01, 5.050e+01,
       3.830e+01, 2.220e+01, 2.460e+01, 3.360e+01, 5.370e+01, 6.530e+01,
       3.000e+01, 2.050e+01, 3.340e+01, 3.790e+01, 4.240e+01, 3.150e+01,
       2.710e+01, 3.450e+01, 1.470e+01, 5.950e+01, 5.850e+01, 3.580e+01,
       3.300e+01, 4.640e+01, 2.240e+01, 3.760e+01, 4.650e+01, 4.050e+01,
       4.020e+01, 3.670e+01, 1.830e+01, 7.540e+01, 3.200e+01, 3.080e+01,
       3.110e+01, 6.210e+01, 3.180e+01, 4.860e+01, 4.280e+01, 7.370e+01,
       2.940e+01, 4.780e+01, 3.090e+01, 8.370e+01, 5.190e+01, 5.200e+01,
       5.680e+01, 7.250e+01, 2.780e+01, 3.950e+01, 8.960e+01, 5.080e+01,
       8.570e+01, 5.090e+01, 8.990e+01, 2.530e+01, 4.250e+01, 3.920e+01,
       2.350e+01, 2.160e+01, 2.130e+01, 2.230e+01, 3.630e+01, 4.180e+01,
       9.600e+01, 5.860e+01, 4.150e+01, 3.800e+01, 5.650e+01, 1.125e+02,
       5.900e+01, 6.400e+01, 4.230e+01, 5.880e+01, 5.250e+01, 7.200e+01,
       6.430e+01, 6.690e+01, 3.420e+01, 4.100e+01, 5.270e+01, 1.810e+01,
       4.270e+01, 3.510e+01, 5.320e+01, 5.390e+01, 9.200e+01, 1.930e+01,
       7.450e+01])

In [13]:
df.incident_month.unique()

array([ 7,  1,  3,  8,  2, 11,  9,  6,  4,  5, 10, 12])

In [8]:
df_copy = df.copy()

In [9]:
df.isna().sum().sum()

np.int64(0)

In [10]:
unique = df["incident_place"].unique()
print(unique)

<StringArray>
[      'adabar',       'adabor',   'aftabnagar',      'airport',
      'ashulia',        'badda',     'bangshal',    'baridhara',
    'bhasantek',      'bhatara',
 ...
    'sreenagar',       'tarail',   'bhedarganj', 'bhurungamari',
       'zajira',   'chitalmari',   'doulatkhan',    'kalukhali',
     'phulbari',     'rajarhat']
Length: 660, dtype: str

In [11]:
for item in unique:
    print(item)

adabar
adabor
aftabnagar
airport
ashulia
badda
bangshal
baridhara
bhasantek
bhatara
banasree
bongshal
bangladesh university of engineering and technology
cantonment
chawkbazar
uttarkhan
dakkhinkhan
darus salam
demra
dhaka university
dhamrai
dhanmondi
domar
donia
gabtoli
gulshan
hazaribagh
hrishikesh das lane
ibrahimpur
islambagh
jatrabari
jurain
kafrul
kalabagan
kalyanpur
kamrangirchar
karail
keraniganj
khilgaon
kuril
lalbagh
malibagh
manda
mirpur
moghbazar
mohakhali
mohammadpur
monipur
mugda
nakhalpara
new market
niketan
old dhaka
pallabi
ramna
rampura
rupnagar
korail
savar
shah ali
shahbagh
shanir akhra
shankaribazar
shekhertek
shewrapara
shyampur
sutrapur
taltola
tejgaon
tikatuli
turag
uttara
vatara
agargaon
aricha highway
banani
bhashantek
dhaka
kalachandpur
madhubagh
sobujbagh
dhaka medical college
manikganj
elephant road
green road
gulistan
jamtala
kadamtali
kakrail
kodomtoli
kurmitola
muslim nagar
sabujbagh
natunbazar
nawabganj
paltan
rayebazar
shantibagh
sher-e-bangla nagar
tongi
topekhana road
amin bazar
azimpur
babubazar bridge
baitul mukarram
bangla motor
bijoynagar
chankharpool
dhaka commerce college
darussalam
dholaikhal
dholaipar
eskaton
eden mohila college
gandaria
gausia
goran
hatirjheel
hatirpool
ideal college
jagannath university
jahangirnagar university
jhigatola
kachukhet
kamalapur railway station
kaptan bazar
khamarbari
khilkhet
maniknagar
motijheel
munni shoroni
nawabpur
new eskaton
nilkhet
panthapath
patuatuli
saidabad bus terminal
shyamoli
suhrawardy udyan
tangail
wari
anandabazar
azampur
badamtoli ghat
bailey road
bashundhara residential area
basundhara residential area
bijoy sarani
boroghortola
buriganga
dakkhin dania
munda
dohar
dogair noorbag
fakirapool
farmgate
hazrat shahjalal international airport
kalayanpur
karwan bazar
kathalbagan
kotwali
manik mia avenue
matikata
matuail
mouchak
muradpur
nababpur
bandar
rayerbazar
razabazar
sayedabad
sir salimullah medical college
t and t colony
jamgora
khalek market
modhubagh
lalmatia
rayerbagh
shaheed suhrawardy medical college hospital
bheribandh
companiganj
dayaganj
dhakeshwari
dhalpur
eastern plaza market
fulbaria
gazipur
hajipara
jigatola
rajabazar
saidpur
segunbagicha
shahjahanpur
shajahanpur
shonir akhra
tanti bazar
banshkhali
boalkhali
chandanaish
fatikchhari
hathazari
karnafuli
lohagara
mirsharai
chattogram city
patiya
rangunia
raozan
sandwip
satkania
sitakunda
anwara
chandgaon
pahartali
chittagong university
agrabad
chittagong medical college
bahaddarhat
dampara
uttar kattali
patenga
gouriakhali beach
galachipa
rajshahi city
fultola
khulna city
raigonj
raipura
raipur
gior
kuakata sea beach
jashore
south sunamganj
bhola
satkhira
gopalganj
habiganj sadar
rajshahi central jail
rajshahi university
rangpur cantonment
sirajganj
bangabandhu safari park
rangpur
sylhet
dinajpur
rowmari
rajshahi university of engineering and technology
rangamati
abhaynagar
aditmari
agailjhara
ajmiriganj
akhaura
akkelpur
alamdanga
alikadam
amtali
araihazar
ashuganj
assasuni
atghoria
atpara
atrai
atwari
austagram
babuganj
badargonj
bagerhat sadar
baghaichari
bagmara
bahubal
bajitpur
bakerganj
baliakandi
banaripara
bandarban sadar
baniachong
baraigram
barguna sadar
barhatta
barisal sadar
barlekha
basail
bauphal
beanibazar
begumganj
belaichari
belkuchi
bera
bhairab
bhaluka
bhandaria
bhanga
bhangura
bheramara
bholahat
bhuapur
birampur
birganj
birol
bishwanath
boalmari
bochaganj
boda
bogra sadar
bokshiganj
botiaghata
brahmanbaria sadar
brahmanpara
chandina
chapainawabganj sadar
charbhadrasan
charfesson
chatmohar
chauddagram
chhatak
chilmari
chirirbandar
chougachha
chunarughat
comilla sadar
coxsbazar sadar
daganbhuiyan
dakshinsurma
damurhuda
dashmina
daudkandi
daulatpur
debidwar
debiganj
delduar
derai
dewangonj
dharmapasha
dhunot
dighinala
digholia
dimla
dinajpur sadar
dumki
durgapur
faridgonj
faridpur
faridpur sadar
fenchuganj
fulbari
gabtali
gafargaon
gaibandha sadar
gangachara
gangni
gazipur sadar
ghatail
ghoraghat
goalanda
gobindaganj
godagari
golapganj
gomostapur
gopalganj sadar
gopalpur
gouripur
gournadi
gowainghat
gurudaspur
hajiganj
hakimpur
haluaghat
harinakundu
haripur
hatia
hatibandha
hizla
ishurdi
islampur
iswarganj
jaldhaka
jamalpur sadar
jessore sadar
jhenaidah sadar
jhikargacha
joypurhat sadar
juri
kachua
kahaloo
kaharol
kalai
kalapara
kalaroa
kalia
kaliganj
kalihati
kalmakanda
kamalnagar
kamarkhand
kamolganj
kanaighat
kapasia
kaptai
karimgonj
kasba
kashiani
kathalia
katiadi
kaunia
kazipur
kendua
keshabpur
khagrachhari sadar
khaliajuri
khansama
kishoreganj sadar
kishorganj
koyra
kulaura
kuliarchar
kumarkhali
kushtia sadar
lakhai
lakshmipur sadar
lalmohan
lalmonirhat sadar
lalpur
lama
louhajanj
madarganj
madaripur sadar
madhabpur
madhukhali
madhupur
magura sadar
manikchari
manikganj sadar
manirampur
mathbaria
matiranga
mehendiganj
meherpur sadar
melandah
mirzaganj
mirzapur
mithapukur
mohalchari
moheshkhali
moheshpur
mohonpur
mollahat
monpura
morrelganj
moulvibazar sadar
muksudpur
muktagacha
munshiganj sadar
muradnagar
mymensingh sadar
chandpur sadar
sirajganj sadar
narayanganj sadar
bagherpara
feni sadar
pirojpur sadar
nabiganj
narsingdi sadar
shalikha
rangamati sadar
sylhet sadar
rajasthali
singiar
rajbari sadar
chuadanga sadar
tangail sadar
nandail
netrokona sadar
pabna sadar
shahjadpur
rangpur sadar
narail sadar
ullapara
panchari
wazirpur
nalchity
panchbibi
thakurgaon sadar
noakhali sadar
sharsha
pirgonj
satkhira sadar
naogaon sadar
nilphamari sadar
shibaloy
raninagar
sarishabari
bhola sadar
zianagar
kotchandpur
nokla
nondigram
khetlal
nabinagar
nagarkanda
nagarpur
naikhongchhari
naniarchar
naria
nasirnagar
natore sadar
nazirpur
nesarabad
nikli
paba
pakundia
palashbari
panchagarh sadar
pangsa
parbatipur
pathorghata
patnitala
patuakhali sadar
phulchari
phulpur
pirgacha
pirganj
purbadhala
rajapur
rajnagar
rajoir
ramgarh
rampal
ramu
ranisankail
rupganj
rupsha
sadarpur
sadullapur
saghata
sakhipur
saltha
santhia
sarail
sarankhola
saturia
senbug
shailkupa
shariakandi
sherpur
sherpur sadar
shibchar
shibganj
shibpur
shyamnagar
singra
sirajdikhan
sonagazi
sonaimori
sonargaon
sonatala
sreemangal
sreepur
subarnachar
sujanagar
sunamganj sadar
sundarganj
tala
tarash
teknaf
terokhada
tetulia
thanchi
tongibari
trishal
tungipara
ukhiya
adamdighi
alfadanga
baliadangi
bancharampur
belabo
betagi
burichang
chakaria
chhagalnaiya
kaliakair
dhanbari
dowarabazar
fakirhat
gosairhat
harirampur
jagannathpur
kabirhat
kalkini
kawkhali
khoksa
kotalipara
langadu
mongla
kurigram sadar
syedpur
dupchanchia
jhalakathi sadar
shariatpur sadar
patgram
nalitabari
niamatpur
palash
pekua
puthia
ramganj
ramgati
rowangchhari
sapahar
sreebordi
tahirpur
tanore
taragonj
zakiganj
badalgachi
bagatipara
bagha
chauhali
haimchar
hossainpur
jaintiapur
jamalganj
jibannagar
mujibnagar
muladi
bishwambarpur
munshiganj
doulatpur
nachol
shalla
balaganj
charghat
chatkhil
damudya
debhata
debahata
dumuria
gajaria
homna
itna
jhenaigati
laksam
monohargonj
lalmonirhat
nageshwari
nangalkot
porsha
ruma
shahrasti
sreenagar
tarail
bhedarganj
bhurungamari
zajira
chitalmari
doulatkhan
kalukhali
phulbari
rajarhat